---
title: "Deviance Patterns of Sociology Students"
author: "SOC& 101"
date: "October 25, 2016"
output: html_document
---

```{r, echo=FALSE, message=FALSE, results="hide", error=FALSE, warning=FALSE}
library(ggplot2); library(dplyr); library(googlesheets); library(scales)

## Authorize the googlsheets package
gs_auth()

## Check Google Sheets user and authentication (auth) status
gs_user()

## List my Google sheets
mysheets <- gs_ls()

## Grab the sheet 'deviance'
deviance <- gs_title('deviance')

## Read in as a dataframe (also as 'tbl_df' and 'tbl')
deviance_df <- gs_read(deviance)
```

# What can we say about our sample?

Our sample contains twice as many females as males.

```{r, echo=FALSE, results='hide'}
gender.counts <- table(deviance_df$gender)
gender.counts_df <- as.data.frame(gender.counts)
gender.counts_df <- dplyr::rename(gender.counts_df, Gender=Var1, Frequency=Freq)
```

```{r, echo=FALSE}
knitr::kable(gender.counts_df)
```

```{r, echo=FALSE}
gender.age <- ggplot(deviance_df, aes(x=age, fill=gender)) + theme_bw()
gender.age + geom_bar(position="dodge")
```

```{r, echo=FALSE}
deviance_df2 <- group_by(deviance_df, age, gender) %>%
  summarise(count = n()) %>%
  mutate(perc=count/sum(count))

ggplot(deviance_df2, aes(x=age, y=perc, fill=gender)) + geom_bar(position = "identity", alpha=0.8) + theme_bw() + labs(x="Age", y="Percent")

deviant <- ddply(d)
